# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target "BasicDemo" do
  pod "RMCoreDataStack", :path => "../"
end

# Uncomment the following lines to add testing dependencies
# target "BasicDemoTests" do
#   pod 'Expecta'
# end